### ISSUE TITLE
is two transitions enough for the actions like 5255B, 5231D, ...

### ISSUE THREAD

**Issue by Picasso-Wang** [xujinglin/FineDiving#5]
Hi. Thank you for the awesome FineDiving dataset. 
I have a tiny question about the transition annotation. For actions starting with 5, like 5255B, 5231D, ..., there are four step in these actions, i.e. [preparation, twist, somersault, entry]. I am wondering how do you separate these actions with two transitions.
Actually, I did some deduction based on some videos:
for video FINAWorldChampionships2019_Women10m_final_r5/3, I find that the separation method is [preparation || twist  somersault || entry];
for video 03/73,  I find that the separation method is [preparation || twist ||  somersault  entry].
I get a little bit confused by these transition annotations. Would you please give me some hints?

**Comment by xujinglin** [comment]
Hi, thanks for your interest in our work.

In our experiments, we kept the number of step transitions L equal to 2, which divides a dive action into three steps: take-off, flight, and entry. If _flight_ is accomplished by a single sub-action type, a dive action is divided into three steps, e.g., 307C. If _flight_ is accomplished by two sub-action types successively, a dive action is divided into four steps, e.g., 6241B. If _flight_ is accomplished by two sub-action types and one sub-action type is interspersed in another, a dive action is divided into five steps, e.g., 5152B. However, the third case (a few actions beginning with 5) is more complicated because the timestamps of performing twist during somersault are not the same for different athletes, resulting in a few actions containing 5 steps that are not obvious. As a result, we take the vast majority of actions (i.e., actions beginning with 5) that can be obviously split into 5 steps (i.e., forword, 2.5 soms.pike, 1 twist, 2.5 soms.pike, entry) as standard, and then few actions (i.e., actions beginning with 5) are also divided into 5 steps to ensure that actions belonging to the same action type have the same number of step transitions.
